// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALhaVo6ORh3ZZD3Iz1kvuJkkJGRRY32IU',
    appId: '1:525052102230:web:d191d5c2929c74009dddf7',
    messagingSenderId: '525052102230',
    projectId: 'falcons-attendance',
    authDomain: 'falcons-attendance.firebaseapp.com',
    storageBucket: 'falcons-attendance.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUd7t71QhI4ATIQil7atmg8_l61NYvfeU',
    appId: '1:525052102230:android:e43258b7038297c79dddf7',
    messagingSenderId: '525052102230',
    projectId: 'falcons-attendance',
    storageBucket: 'falcons-attendance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApbvMiZZs3Zi9LHvRIvRPG_HTZy3nuZ0A',
    appId: '1:525052102230:ios:4e521e5a9d3b69cc9dddf7',
    messagingSenderId: '525052102230',
    projectId: 'falcons-attendance',
    storageBucket: 'falcons-attendance.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApbvMiZZs3Zi9LHvRIvRPG_HTZy3nuZ0A',
    appId: '1:525052102230:ios:4e521e5a9d3b69cc9dddf7',
    messagingSenderId: '525052102230',
    projectId: 'falcons-attendance',
    storageBucket: 'falcons-attendance.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALhaVo6ORh3ZZD3Iz1kvuJkkJGRRY32IU',
    appId: '1:525052102230:web:d6f015e47ee213b99dddf7',
    messagingSenderId: '525052102230',
    projectId: 'falcons-attendance',
    authDomain: 'falcons-attendance.firebaseapp.com',
    storageBucket: 'falcons-attendance.firebasestorage.app',
  );

}